###eureka 服务端口号
server:
  port: ${port}
spring:
  application:
    name: consul-order
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        ###服务地址默认为ip地址 默认情况下服务注册到注册中心地址随机生成英文地址
        hostname: 127.0.0.1
