###eureka 服务端口号
server:
  port: ${port}
spring:
  application:
    name: consul-member
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
