server:
  port: 80
####服务网关名称
spring:
  application:
    name: mayikt-gateway
  cloud:
    gateway:
      ###开启以服务id去注册中心上获取转发地址
      discovery:
        locator:
          enabled: true
        ###路由策略
      routes:
      ###路由id
      - id: member
        ####基于lb负载均衡形式转发
        uri: lb://kk-member
        filters:
         - StripPrefix=1
        ###匹配规则
        predicates:
         - Path=/member/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848